### ISSUE TITLE
Free Code Camp London description may be misleading

### ISSUE THREAD

**Issue by chris-alexander** [lnug/related-meetups#17]
The current description for Free Code Camp London 'Learn to code and help nonprofits'  may suggest that the organisers have a say when an individual can work on a project for a non-profit. However, the reality is that you can only get to this stage if you complete all of the challenges on the FCC curriculum. (See here: <https://www.quora.com/I-want-to-help-nonprofits-through-Free-Code-Camp-I-am-already-an-experienced-engineer-Do-I-still-need-to-complete-the-first-800-hours-of-the-JavaScript-curriculum>) The description therefore could be misleading to experienced developers who are interested in the non-profit projects. Most (if not all) of those in our study group so far have not reached this stage yet.

I have submitted a PR already with an updated description. Please let me know what you think.

**Comment by iancrowther** [comment]
merged.

its your meetup and so the description should be led by you.  many thanks for the PR
